name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.10' 
          
      - name: Restore NuGet Packages
        run: nuget restore AMS2ToApexRivals.sln

      - name: Build
        run: dotnet build AMS2ToApexRivals.sln --configuration Release --no-restore
  
      - name: Publish (Optional)
        run: dotnet publish AMS2ToApexRivals.csproj --configuration Release --output ./publish
     
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Build-Artifacts
          path: ./publish
