name: Main

on: 
  push:
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore NuGet Packages
        run: dotnet restore AMS2ToApexRivals.sln

      - name: Build
        run: dotnet build AMS2ToApexRivals.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish AMS2TARApp/AMS2TARApp.csproj --configuration Release --output ./publish

      - name: List Publish Directory
        run: |
          echo "Contents of the publish directory:"
          dir ./publish

      - name: Create ZIP of Publish Directory
        run: Compress-Archive -Path ./publish/* -DestinationPath ./publish/AMS2ToApexRivals.zip

      - name: Create and Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./publish/AMS2TARApp.exe
            ./publish/AMS2TARApp.deps
            ./publish/AMS2TARApp.dll
            ./publish/AMS2TARApp.pdb
            ./publish/AMS2TARApp.runtimeconfig
            ./publish/MaterialDesignColors.dll
            ./publish/MaterialDesignThemes.Wpf.dll
            ./publish/Microsoft.Xaml.Behaviors.dll
            ./publish/AMS2ToApexRivals.zip # Optional: Include ZIP file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Build-Release
          path: ./publish/
